> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- np.concatenate
- np.sum
- np.reshape
- np.max
- np.min

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalpal622003/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalpal622003/numpy-array-operations


'https://jovian.ai/vishalpal622003/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = np.sum
function3 = np.reshape
function4 = np.max
function5 = np.min

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [6]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [7]:
# Example 2 - working
arr1 = [[2, 1, 8], 
        [5, 4, 9]]

arr2 = [[0, 1, 3], 
        [9, 2, 22]]

np.concatenate((arr1, arr2), axis=1)

array([[ 2,  1,  8,  0,  1,  3],
       [ 5,  4,  9,  9,  2, 22]])

Explanation about example

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalpal622003/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalpal622003/numpy-array-operations


'https://jovian.ai/vishalpal622003/numpy-array-operations'

## Function 2 - np.sum

Add some explanations

In [10]:
# Example 1 - working
arr=[2,3,4,5]
np.sum(arr)

14

Explanation about example

In [11]:
# Example 2 - working
arr=[[1,2,3],[4,5,6]]
np.sum(arr)

21

Explanation about example

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr=[[1,2,3],["riya"]]
np.sum(arr)

/opt/conda/lib/python3.8/site-packages/numpy/core/fromnumeric.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[1, 2, 3, 'riya']

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalpal622003/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalpal622003/numpy-array-operations


'https://jovian.ai/vishalpal622003/numpy-array-operations'

## Function 3 - np.reshape

Add some explanations

In [14]:
# Example 1 - working
arr=[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]
np.reshape(arr,(3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Explanation about example

In [15]:
# Example 2 - working
arr=[[ 0,  1,  2, 3],  [4,  5,  6,  7],  [8,  9, 10, 11]]
np.reshape(arr,(4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Explanation about example

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
arr=[[ 0,  1,  2, 3],  [4,  5,  6,  7],  [8,  9, 10, 11]]
np.reshape(arr,(1,2))

ValueError: cannot reshape array of size 12 into shape (1,2)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalpal622003/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalpal622003/numpy-array-operations


'https://jovian.ai/vishalpal622003/numpy-array-operations'

## Function 3 - np.max

Add some explanations

In [19]:
# Example 1 - working
arr=[[ 0,  1,  2, 3],  [4,  5,  6,  7],  [8,  9, 10, 11]]
np.max(arr)

11

Explanation about example

In [20]:
# Example 2 - working
arr=[ 0,  1,  2, 8,  9, 10, 66]
np.max(arr)

66

Explanation about example

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
arr=[ 0,  1,  2, 8,  "9", 10, 66]
np.max(arr)

TypeError: cannot perform reduce with flexible type

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalpal622003/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalpal622003/numpy-array-operations


'https://jovian.ai/vishalpal622003/numpy-array-operations'

## Function 4 - np.min

Add some explanations

In [23]:
# Example 1 - working
arr=[  8,  9, 10, 66]
np.min(arr)

8

Explanation about example

In [24]:
# Example 2 - working
arr=[[ 0,  1,  2, 3],  [4,  5,  6,  7],  [8,  9, 10, 11]]
np.min(arr)

0

Explanation about example

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
arr=[[ 0,  1,  2, 3],  [-4,  5,  6,  7],  ["8",  9, 10, 11]]
np.min(arr)

TypeError: cannot perform reduce with flexible type

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "vishalpal622003/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/vishalpal622003/numpy-array-operations


'https://jovian.ai/vishalpal622003/numpy-array-operations'

## Function 5 - np.append

Add some explanations

In [27]:
# Example 1 - working
a=([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
np.append(a,b)

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

Explanation about example

In [28]:
# Example 2 - working
a=([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
np.append(a,b,axis=0)  


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

Explanation about example

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
a=([[10, 20, 30], [40, 50, 60], [70, 80]])  
b=([[11, 21], [42, 52, 62], [73, 83, 93]])  
np.append(a,b)

/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


array([list([10, 20, 30]), list([40, 50, 60]), list([70, 80]),
       list([11, 21]), list([42, 52, 62]), list([73, 83, 93])],
      dtype=object)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()